name: flutter_bloc_state_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <=3.13.3'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/