name: data_layer
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.2

flutter:
