// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoSLnmgguDguQNyxRYKG7U-YQzfSkICJk',
    appId: '1:179757166758:web:42e353a24204d53c4e4467',
    messagingSenderId: '179757166758',
    projectId: 'purchases-e1954',
    authDomain: 'purchases-e1954.firebaseapp.com',
    storageBucket: 'purchases-e1954.appspot.com',
    measurementId: 'G-CHSY9SLPKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRdWiLWBaBZxNfISnelW0Pzwafvt93NY',
    appId: '1:179757166758:android:5522861576275ba64e4467',
    messagingSenderId: '179757166758',
    projectId: 'purchases-e1954',
    storageBucket: 'purchases-e1954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD7xevNg_lQAdkRoHkEqBDNn1wa4VLoVY',
    appId: '1:179757166758:ios:5180787e7867d9ad4e4467',
    messagingSenderId: '179757166758',
    projectId: 'purchases-e1954',
    storageBucket: 'purchases-e1954.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD7xevNg_lQAdkRoHkEqBDNn1wa4VLoVY',
    appId: '1:179757166758:ios:5c006d41716ac3a34e4467',
    messagingSenderId: '179757166758',
    projectId: 'purchases-e1954',
    storageBucket: 'purchases-e1954.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
